### ISSUE TITLE
'cordova-plugin-ios-xhr' is not in the npm registry

### ISSUE THREAD

**Issue by svenemtell** [globules-io/cordova-plugin-ios-xhr#4]
Not sure if this is a bug or if I'm doing something unexpected.
My environment:
```
node 10.22
npm 6.14.6
cordova 10.0.0
cordova-ios 6.1.0
ios-deploy 1.11.0
```
1. I install using
`cordova plugin add @globules-io/cordova-plugin-ios-xhr`
which results in an added line in package.json cordova/plugins
`"cordova-plugin-ios-xhr": {}`
(When installing other plugins I also get a line with the plugin version or a git url in package.json devDependencies!?)
2. As part of my build process I do
```
rm -fr node_modules
rm -fr plugins
rm -fr platforms
cordova platform add ios
```
which results in
```
Discovered plugin "cordova-plugin-ios-xhr". Adding it to the project
Command failed with exit code 1: npm view cordova-plugin-ios-xhr --json
npm ERR! code E404
npm ERR! 404 'cordova-plugin-ios-xhr' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404 
npm ERR! 404  'cordova-plugin-ios-xhr@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sven/.npm/_logs/2020-08-11T21_15_18_934Z-debug.log
{
  "error": {
    "code": "E404",
    "summary": "'cordova-plugin-ios-xhr' is not in the npm registry.\nYou should bug the author to publish it\n(or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url.",
    "detail": "\n 'cordova-plugin-ios-xhr@latest' is not in the npm registry.\nYou should bug the author to publish it (or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}
```

**NOTE:**
If I instead install using
`cordova plugin add https://github.com/globules-io/cordova-plugin-ios-xhr`
I get this line in package.json cordova/plugins
`"cordova-plugin-ios-xhr": {}`
and also this line in package.json devDependencies
`"@globules-io/cordova-plugin-ios-xhr": "git+https://github.com/globules-io/cordova-plugin-ios-xhr.git"`
If I manually add `"@globules-io/cordova-plugin-ios-xhr": {}` to package.json cordova/plugins everything seems to work as expected!

**Comment by globules-io** [comment]
Here we're setting the plugin in config.xml

     <plugin name="@globules-io/cordova-plugin-ios-xhr" spec="^1.0.3" />

Which creates in package.lock

```
    "@globules-io/cordova-plugin-ios-xhr": {
      "version": "1.0.3",
      "resolved": "https://registry.npmjs.org/@globules-io/cordova-plugin-ios-xhr/-/cordova-plugin-ios-xhr-1.0.3.tgz",
      "integrity": "sha512-mFpnSuNkoPWel2K0uGFONj31tx4ud+E3nCKKe1uj1jYaj43gtRA1HDbPReqQyut8buQkShZKskYK/ofbdRRyxQ==",
      "dev": true
    },
```

I will try adding it from the console... Meanwhile, can you just use config.xml ?

**Comment by globules-io** [comment]
Here's my test

cordova create test
cd test
cordova plugin add @globules-io/cordova-plugin-ios-xhr

package:
```
"devDependencies": {
    "@globules-io/cordova-plugin-ios-xhr": "^1.0.3",
    "cordova-plugin-whitelist": "^1.3.4"
  },
```

package lock

```
"dependencies": {
    "@globules-io/cordova-plugin-ios-xhr": {
      "version": "1.0.3",
      "resolved": "https://registry.npmjs.org/@globules-io/cordova-plugin-ios-xhr/-/cordova-plugin-ios-xhr-1.0.3.tgz",
      "integrity": "sha512-mFpnSuNkoPWel2K0uGFONj31tx4ud+E3nCKKe1uj1jYaj43gtRA1HDbPReqQyut8buQkShZKskYK/ofbdRRyxQ==",
      "dev": true
    }
  }

```

Also not sure why you remove node_modules and plugins and platforms ??

**Comment by svenemtell** [comment]
I downloaded the code and made following changes.

**package.json**
Replaced
```
  "cordova": {
    "id": "cordova-plugin-ios-xhr",
```
with
```
  "cordova": {
    "id": "@globules-io/cordova-plugin-ios-xhr",
```
**plugin.xml**
Replaced
```
<plugin xmlns="http://apache.org/cordova/ns/plugins/1.0"
    id="cordova-plugin-ios-xhr"
```
with
```
<plugin xmlns="http://apache.org/cordova/ns/plugins/1.0"
    id="@globules-io/cordova-plugin-ios-xhr"
```
After that I could install it locally using
`cordova plugin add <path>`
and it worked as I expected.
I could also cleanly uninstall it using
`cordova plugin rm @globules-io/cordova-plugin-ios-xhr`
(See #6)

**Comment by svenemtell** [comment]
> Also not sure why you remove node_modules and plugins and platforms ??

I did the following to make sure that it is a clean build.
```
rm -fr node_modules
rm -fr plugins
rm -fr platforms
cordova platform add ios
```
**NOTE:**
I don't use a package-lock.json for this project for legacy reasons.

Maybe there is a better way to ensure a clean build?

**Comment by mg** [comment]
Hi, I realize this has been closed, but I think this is still a problem.

I have the following in my package.json:
![image](https://user-images.githubusercontent.com/1972/90527940-9c628100-e161-11ea-8c7b-7a0212ca8d2d.png)
Now when I do ``cordova platform add ios@6.1.0`` (which is what happens on our build server) the process fails with the following:

```
Failed to restore plugin "cordova-plugin-ios-xhr". You might need to try adding it again. Error: Error: Command failed with exit code 1: npm view cordova-plugin-ios-xhr --json
npm ERR! code E404
npm ERR! 404 'cordova-plugin-ios-xhr' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404 
npm ERR! 404  'cordova-plugin-ios-xhr@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/magnusorngylfason/.npm/_logs/2020-08-18T14_32_31_483Z-debug.log
{
  "error": {
    "code": "E404",
    "summary": "'cordova-plugin-ios-xhr' is not in the npm registry.\nYou should bug the author to publish it\n(or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url.",
    "detail": "\n 'cordova-plugin-ios-xhr@latest' is not in the npm registry.\nYou should bug the author to publish it (or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}
```

If I try to run the command ``npm view cordova-plugin-ios-xhr --json`` it fails, but running ``npm view @globules-io/cordova-plugin-ios-xhr --json`` works. So something in this repo is causing the installation process to attempt to fetch info for ``cordova-plugin-ios-xhr``when it should be fetching info for ``@globules-io/cordova-plugin-ios-xhr^``. My money is on the plugin-id in the package.json file:
![image](https://user-images.githubusercontent.com/1972/90528485-3296a700-e162-11ea-8d5b-96652081cf37.png)

**Comment by globules-io** [comment]
Fixed for you in 1.0.7

**Comment by mg** [comment]
Hi, seems it did not fix the issue.

The plugin.xml issue is still claiming version 1.0.6, isn't that a problem?

<img width="576" alt="image" src="https://user-images.githubusercontent.com/1972/90620478-0a5e8500-e202-11ea-84a2-5d3ade586edc.png">

**Comment by globules-io** [comment]
WHAT IS THE BUG??????
please stop msg me, fix, do a PR or just use your own shit

**Comment by souly1** [comment]
Hi,
still unable to install and same error when using "cordova add" as written in readme...

**Comment by danemco** [comment]
I'm getting the same issue as @souly1
